#!/usr/bin/env bash

# Функция для вывода успешного сообщения зеленым цветом
print_success() {
  local GREEN='\033[0;32m'
  local NC='\033[0m' # No Color
  echo -e "${GREEN}Success: $1${NC}"
}

# Функция для вывода ворнинга с желтым цветом
print_warning() {
  local YELLOW='\033[1;33m'
  local NC='\033[0m' # No Color
  echo -e "${YELLOW}Warning: $1${NC}"
}

# Функция для вывода ошибки с красным цветом
print_error() {
  local RED='\033[1;31m'
  local NC='\033[0m' # No Color
  echo -e "${RED}Error: $1${NC}"
}

if [[ "$(uname -m)" == arm64 ]]; then
    export PATH="/opt/homebrew/bin:$PATH"
fi

if ! command -v swiftlint &> /dev/null; then
    print_warning "SwiftLint not installed, download from https://github.com/realm/SwiftLint"
    exit 1
fi

changed_files=$(git diff --name-only --cached --diff-filter=ACMR | grep -E "\.(swift)$")

lint_failed=false

for file in $changed_files; do
  if [ -f "$file" ]; then
    output=$(swiftlint --quiet "$file")
    if [ -n "$output" ]; then
      lint_failed=true
      print_warning "$output"
    fi
  fi
done

echo

if $lint_failed; then
  print_error "Errors or warnings found. Commit aborted."
  exit 1
else
  print_success "No errors or warnings found. Committing..."
  exit 0
fi